spring:
  application:
    name: transfusionQueryService
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/rcapp
    username: milos
    password: 1234
server:
  port : 8080
application:
  jwt:
    secretKey: dadasdasdasdasdasdasdasdasdasdasdasasdasdasddadasdasdasdasdasdasdasdasdasdasdasasdasdasddadasdasdasdasdasdasdasdasdasdasdasasdasdasd
    tokenPrefix: "Bearer "
    tokenExpirationAfterMinutes: 14
