server:
  port: 8079

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application.name: gatewayService
  redis:
    connect-timeout: 30s
    host: localhost
    port: 6379
    timeout: 5s
  cloud:
    gateway:
      default-filters:
      - name: Retry
        args:
          retries: 3
          statuses: BAD_GATEWAY
          methods: GET,POST
          backoff:
            firstBackoff: 50ms
            maxBackoff: 500s
            factor: 2
            basedOnPreviousValue: false
      - name: RequestRateLimiter
        args:
          redis-rate-limiter.replenishRate: 10
          redis-rate-limiter.burstCapacity: 20
          redis-rate-limiter.requestedTokens: 1
      - name: CircuitBreaker
      routes:
        - id: authProviderService-login
          uri: lb://authProviderService
          predicates:
            Path=/login
          filters:
            - SetPath=/api/v1/login
        - id: appUserService-new
          uri: lb://appUserService
          predicates:
            Path=/user/new
          filters:
            - RewritePath=/user/(?<segment>.*), /api/v1/$\{segment}
        - id: confirmacionTokenService-confirm
          uri: lb://confirmationTokenService
          predicates:
            Path=/confirm/**
          filters:
            - RewritePath=/confirm/(?<segment>.*), /api/v1/confirm/$\{segment}
        - id: confirmacionTokenService-confirm
          uri: lb://donorService
          predicates:
            Path=/donor/**
          filters:
            - RewritePath=/donor/(?<segment>.*), /api/v1/$\{segment}
            - AuthFilter=ADMIN,USER,ADMIN_MEDIC,USER_MEDIC
